services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ~/.aws/:/root/.aws/
    ports:
      - "3000:3000"
    tty: true
    # command: sh -c "yarn install && yarn dev"
